"""フェーズ2：中学英語 全17単元 単元プリント（各8問）。"""
from ._common import desc, mc, order, sa, stim, table, unit_set

PHASE = 2
Q = "（　）に入る最も適切なものを選びなさい。\n"
O = "日本語に合うように、語句を並べかえなさい。ただし、文頭にくる語も小文字で示してある。\n"
R = ["reading"]
W = ["writing", "grammar"]


def U(unit_id, items, **kw):
    return unit_set(unit_id, items, track="junior_high", out=f"data/junior_high/english/{unit_id.lower()}.json", **kw)


SETS = [
    U("JH-ENG-G1-U01", [
        mc(Q + "I (　　) a junior high school student.", ["am", "is", "are", "be"], "主語が I のときの be 動詞は am。", d=1),
        mc(Q + "My sister (　　) tennis every day.", ["plays", "play", "playing", "is play"], "主語が3人称単数で現在の習慣を表すので、動詞に -s をつける。", d=1),
        mc(Q + "(　　) you like music?", ["Do", "Are", "Does", "Is"], "一般動詞 like の疑問文で、主語が you なので Do を文頭に置く。", d=1),
        mc(Q + "Ken (　　) have a dog.", ["doesn't", "don't", "isn't", "aren't"], "一般動詞の否定文で主語が3人称単数なので doesn't ＋動詞の原形。", d=1),
        sa("次の英文を否定文に書きかえなさい。\nThey are from Canada.", "They are not from Canada.", "be 動詞の否定文は be 動詞の後ろに not を置く。They aren't from Canada. でもよい。",
           d=2, v=["They aren't from Canada.", "They're not from Canada."]),
        sa("次の英文を疑問文に書きかえなさい。\nYour father watches TV after dinner.", "Does your father watch TV after dinner?",
           "主語が3人称単数の一般動詞の文は Does を文頭に置き、動詞を原形（watch）にもどす。", d=2),
        mc("次の質問に対する答えとして最も適切なものを選びなさい。\nDoes Mr. Brown teach English?", ["Yes, he does.", "Yes, he is.", "Yes, he teaches.", "Yes, Mr. Brown do."],
           "Does ～? には does を使って答える。Mr. Brown は he で受ける。", d=2),
        order(O + "私の兄は毎朝 7 時に起きます。", ["my brother", "gets up", "at seven", "every morning"],
              "My brother gets up at seven every morning. 時を表す語句は「時刻→every morning」の順が自然。主語が3人称単数なので gets。", d=3),
    ]),
    U("JH-ENG-G1-U02", [
        sa("box の複数形を書きなさい。", "boxes", "-s, -x, -ch, -sh で終わる名詞は -es をつける。", d=1),
        sa("child の複数形を書きなさい。", "children", "child は不規則に変化する。ほかに man → men、woman → women、foot → feet など。", d=2),
        mc(Q + "This is (　　) bag.", ["my", "I", "me", "mine"], "名詞 bag の前には所有格 my を置く。", d=1),
        mc(Q + "Do you know (　　)? She is our new teacher.", ["her", "she", "hers", "they"], "know の目的語なので目的格 her。", d=1),
        mc(Q + "This notebook is (　　). My name is on it.", ["mine", "my", "me", "I"], "「私のもの」は所有代名詞 mine。後ろに名詞がこない。", d=2),
        mc(Q + "I have two (　　).", ["dictionaries", "dictionary", "dictionarys", "a dictionary"], "two の後ろは複数形。子音字＋y で終わる語は y を i にかえて -es。", d=2),
        mc(Q + "How many (　　) do you have?", ["CDs", "CD", "a CD", "the CD"], "How many の後ろには数えられる名詞の複数形がくる。", d=2),
        sa("下線部を1語の代名詞にかえて、全文を書きなさい。\nI often play with [[u:Tom and Mike]].", "I often play with them.",
           "前置詞 with の後ろなので目的格。Tom and Mike は複数なので them。", d=3),
    ]),
    U("JH-ENG-G1-U03", [
        mc(Q + "(　　) is that girl? ― She is my cousin.", ["Who", "What", "Where", "When"], "人をたずねるときは Who。", d=1),
        mc(Q + "(　　) do you live? ― I live in Yokohama.", ["Where", "When", "What", "How"], "場所をたずねるときは Where。", d=1),
        mc(Q + "(　　) is your birthday? ― It's May 5.", ["When", "Where", "Who", "Which"], "日付・時をたずねるときは When。", d=1),
        mc(Q + "(　　) books do you have? ― I have about fifty.", ["How many", "How much", "How old", "How long"], "数をたずねるときは How many ＋複数名詞。", d=2),
        mc(Q + "(　　) is this pen? ― It's 120 yen.", ["How much", "How many", "What", "Which"], "値段をたずねるときは How much。", d=2),
        mc(Q + "(　　) bike is this? ― It's Yuki's.", ["Whose", "Who", "Which", "What"], "持ち主をたずねるときは Whose ＋名詞。", d=2),
        sa("下線部が答えの中心となる疑問文を書きなさい。\nShe goes to school [[u:by bus]].", "How does she go to school?", "手段・方法をたずねるときは How を使う。", d=3),
        order(O + "あなたは夕食の後に何をしますか。", ["what", "do you", "do", "after dinner"],
              "What do you do after dinner? 最初の do は疑問文をつくる助動詞、2つ目の do は「する」という意味の一般動詞。", d=3),
    ]),
    U("JH-ENG-G1-U04", [
        mc(Q + "Look! The children (　　) in the park.", ["are running", "run", "is running", "runs"], "Look! から「今～している」とわかるので現在進行形。主語は複数なので are。", d=1),
        sa("run の -ing 形を書きなさい。", "running", "短母音＋子音字で終わる語は、最後の文字を重ねて -ing をつける。", d=1),
        mc(Q + "My father (　　) speak Chinese.", ["can", "cans", "can to", "is can"], "助動詞 can は主語に関係なく形が変わらず、後ろに動詞の原形がくる。", d=1),
        mc(Q + "(　　) careful. The road is wet.", ["Be", "Are", "Is", "Do"], "形容詞を使った命令文は Be で始める。", d=2),
        mc(Q + "(　　) play soccer after school. ― Yes, let's.", ["Let's", "Let", "Shall", "Please"], "「～しましょう」は Let's ＋動詞の原形。", d=1),
        sa("次の英文を疑問文に書きかえなさい。\nShe can play the piano.", "Can she play the piano?", "can の疑問文は Can を主語の前に出す。", d=2),
        mc(Q + "What (　　) you doing now? ― I'm reading a book.", ["are", "do", "is", "does"], "現在進行形の疑問文。主語 you に合わせて are。", d=2),
        order(O + "この部屋で写真をとってはいけません。", ["don't", "take", "pictures", "in this room"], "否定の命令文は Don't ＋動詞の原形。Don't take pictures in this room.", d=3),
    ]),
    U("JH-ENG-G1-U05", [
        sa("go の過去形を書きなさい。", "went", "go は不規則動詞。go − went − gone。", d=1),
        sa("study の過去形を書きなさい。", "studied", "子音字＋y で終わる動詞は y を i にかえて -ed。", d=1),
        mc(Q + "I (　　) to Kyoto last summer.", ["went", "go", "goes", "going"], "last summer（去年の夏）とあるので過去形。", d=1),
        mc(Q + "(　　) you watch TV last night?", ["Did", "Do", "Were", "Are"], "一般動詞の過去の疑問文は Did ＋主語＋動詞の原形。", d=1),
        mc(Q + "We (　　) very busy yesterday.", ["were", "was", "are", "did"], "be 動詞の過去形。主語 we には were。", d=2),
        mc(Q + "I (　　) a bath when you called me.", ["was taking", "am taking", "take", "were taking"], "「電話したとき～していた」は過去進行形。主語 I には was。", d=2),
        sa("次の英文を否定文に書きかえなさい。\nShe bought a new bag.", "She didn't buy a new bag.", "didn't の後ろの動詞は原形にもどす（bought → buy）。", d=2, v=["She did not buy a new bag."]),
        order(O + "あなたは昨日どこで昼食を食べましたか。", ["where", "did you", "eat", "lunch", "yesterday"], "Where did you eat lunch yesterday? 疑問詞＋did＋主語＋動詞の原形。", d=3),
    ]),
    U("JH-ENG-G2-U01", [
        mc(Q + "It (　　) rainy tomorrow.", ["will be", "is", "was", "will is"], "tomorrow なので未来。will の後ろは動詞の原形 be。", d=1),
        mc(Q + "I'm going (　　) my grandmother next Sunday.", ["to visit", "visit", "visiting", "visited"], "be going to ＋動詞の原形で「～するつもりだ」。", d=1),
        mc(Q + "(　　) you going to join the party?", ["Are", "Do", "Will", "Is"], "be going to の疑問文は be 動詞を主語の前に出す。", d=1),
        sa("次の英文を否定文に書きかえなさい。\nHe will come here today.", "He will not come here today.", "will の否定は will not（won't）＋動詞の原形。", d=2, v=["He won't come here today."]),
        mc(Q + "A: Will you help me? \nB: (　　)", ["Sure.", "Yes, I am.", "No, I don't.", "Yes, you will."], "Will you ～? は「～してくれませんか」という依頼。Sure. / All right. などで答える。", d=2),
        mc("次の英文とほぼ同じ意味を表すものを選びなさい。\nI'm going to study abroad next year.", ["I plan to study abroad next year.", "I studied abroad last year.", "I'm studying abroad now.", "I want to study abroad every year."],
           "be going to は前から予定していることを表す。plan to ～（～する計画だ）が近い。", d=3),
        sa("日本語に合うように、（　）に入る語を書きなさい。\n明日は晴れるでしょう。\nIt (　　) (　　) sunny tomorrow.", "will be", "未来を表す will ＋ be。", d=2),
        order(O + "あなたは今週末何をするつもりですか。", ["what", "are you", "going to", "do", "this weekend"], "What are you going to do this weekend?", d=3),
    ]),
    U("JH-ENG-G2-U02", [
        mc(Q + "I want (　　) a doctor.", ["to be", "be", "being", "been"], "want to ＋動詞の原形で「～したい」。", d=1),
        mc(Q + "I enjoyed (　　) with my friends.", ["talking", "to talk", "talk", "talked"], "enjoy の後ろは動名詞（-ing 形）。不定詞はとらない。", d=1),
        mc(Q + "She went to the library (　　) some books.", ["to borrow", "borrowing", "borrow", "borrowed"], "「～するために」は副詞的用法の不定詞。", d=2),
        mc(Q + "I have a lot of homework (　　) today.", ["to do", "doing", "do", "done"], "「するべき宿題」と名詞を後ろから説明する形容詞的用法の不定詞。", d=2),
        mc(Q + "(　　) English is interesting.", ["Learning", "Learn", "Learned", "Learns"], "動名詞が主語になる。To learn でも表せるが選択肢にない。", d=2),
        mc(Q + "My brother finished (　　) his room.", ["cleaning", "to clean", "clean", "cleaned"], "finish の後ろは動名詞。", d=2),
        mc("次の2つの英文の意味の違いとして正しいものを選びなさい。\n(1) He stopped talking.\n(2) He stopped to talk.",
           ["(1) は「話すのをやめた」、(2) は「話すために立ち止まった」", "(1) も (2) も「話すのをやめた」", "(1) は「話すために立ち止まった」、(2) は「話すのをやめた」", "(1) も (2) も「話すために立ち止まった」"],
           "stop ～ing は「～するのをやめる」。stop to ～ の to ～ は目的を表す副詞的用法で「～するために立ち止まる（手を止める）」。", d=4, k=["grammar", "thinking"]),
        order(O + "私は何か温かい飲み物がほしい。", ["I want", "something", "hot", "to drink"], "something を修飾する形容詞は後ろに置き、さらに不定詞が続く。I want something hot to drink.", d=4),
    ]),
    U("JH-ENG-G2-U03", [
        mc(Q + "(　　) a cat under the table.", ["There is", "There are", "It is", "They are"], "a cat は単数なので There is。", d=1),
        mc(Q + "I was watching TV (　　) my mother came home.", ["when", "if", "because", "but"], "「母が帰宅したとき」で時を表す when。", d=1),
        mc(Q + "I stayed home (　　) I had a cold.", ["because", "if", "when", "so"], "理由を表す because。", d=1),
        mc(Q + "(　　) it is sunny tomorrow, let's go to the beach.", ["If", "Because", "But", "That"], "条件を表す if。if の文の中は未来のことでも現在形で表す。", d=2),
        mc(Q + "You (　　) wear a seat belt in a car.", ["must", "may", "can't", "need not"], "「～しなければならない」は must。", d=2),
        mc(Q + "You (　　) to get up early tomorrow. It's Sunday.", ["don't have", "must not", "can't", "should not"], "don't have to ～は「～する必要はない」。must not は「～してはいけない」で意味が異なる。", d=3),
        sa("2つの英文がほぼ同じ意味になるように、（　）に入る1語を書きなさい。\nYou must not run in the hallway. \n(　　) run in the hallway.", "Don't",
           "must not（～してはいけない）は、否定の命令文 Don't ～. とほぼ同じ意味を表す。", d=3, v=["Do not"]),
        order(O + "あなたは彼がどこに住んでいるか知っていると思います。", ["I think", "you know", "where", "he lives"], "I think (that) you know where he lives. think の後ろの that が省略されている。", d=4),
    ]),
    U("JH-ENG-G2-U04", [
        mc(Q + "This bridge is (　　) than that one.", ["longer", "long", "longest", "more long"], "than があるので比較級。", d=1),
        mc(Q + "Who can swim (　　) in your family?", ["the fastest", "faster", "fast", "the faster"], "in your family（家族の中で）とあるので最上級。", d=1),
        sa("happy の比較級を書きなさい。", "happier", "子音字＋y で終わる形容詞は y を i にかえて -er。", d=1),
        mc(Q + "This question is (　　) difficult than that one.", ["more", "most", "much", "very"], "difficult は長い語なので more ＋原級で比較級をつくる。", d=2),
        mc(Q + "Ken is as (　　) as his father.", ["tall", "taller", "tallest", "more tall"], "as ～ as の間は原級。", d=2),
        sa("2つの英文がほぼ同じ意味になるように、（　）に入る1語を書きなさい。\nMy room is smaller than yours. \nYour room is (　　) than mine.", "bigger", "small の反対の big を比較級にする。g を重ねる。", d=2, v=["larger"]),
        mc(Q + "I like spring (　　) of all seasons.", ["the best", "better", "best than", "more"], "of all seasons（すべての季節の中で）とあるので like ～ the best。", d=2),
        mc("次の英文と同じ内容を表すものを選びなさい。\nShinji is older than Aki, and Aki is older than Rina.",
           ["Rina is the youngest of the three.", "Aki is the oldest of the three.", "Rina is older than Shinji.", "Shinji is younger than Rina."],
           "年上の順に Shinji、Aki、Rina なので、Rina が3人の中で最も若い。", d=3, k=["grammar", "thinking"]),
    ]),
    U("JH-ENG-G2-U05", [
        mc(Q + "This room is (　　) every day.", ["cleaned", "clean", "cleaning", "cleans"], "「掃除される」は受け身。be 動詞＋過去分詞。", d=1),
        sa("write の過去分詞を書きなさい。", "written", "write − wrote − written。", d=1),
        mc(Q + "English is (　　) in many countries.", ["spoken", "speak", "spoke", "speaking"], "「話されている」は受け身。speak の過去分詞は spoken。", d=1),
        mc(Q + "This temple (　　) built about 500 years ago.", ["was", "is", "were", "has"], "ago があるので過去の受け身。主語は単数で was。", d=2),
        sa("次の英文を受け身の文に書きかえなさい。\nMany people visit this museum.", "This museum is visited by many people.", "目的語を主語にし、be 動詞＋過去分詞＋by ～の形にする。", d=2),
        mc(Q + "The mountain is covered (　　) snow.", ["with", "by", "of", "from"], "be covered with ～で「～でおおわれている」。by 以外の前置詞を使う受け身。", d=3),
        sa("次の英文を疑問文に書きかえなさい。\nThese pictures were taken by Ken.", "Were these pictures taken by Ken?", "受け身の疑問文は be 動詞を主語の前に出す。", d=2),
        order(O + "その歌は若い人たちに愛されていますか。", ["is", "the song", "loved", "by", "young people"], "Is the song loved by young people?", d=3),
    ]),
    U("JH-ENG-G3-U01", [
        mc(Q + "I have (　　) in this town for ten years.", ["lived", "live", "living", "lives"], "have ＋過去分詞の現在完了（継続）。", d=1),
        mc(Q + "Have you ever (　　) to Hokkaido?", ["been", "go", "went", "be"], "「～に行ったことがある」は have been to ～。", d=1),
        mc(Q + "I have (　　) finished my homework.", ["already", "yet", "ever", "since"], "肯定文で「もう～した」は already。yet は疑問文・否定文で使う。", d=1),
        mc(Q + "She has been sick (　　) last Friday.", ["since", "for", "from", "ago"], "起点（～から）を表すのは since。期間を表すのは for。", d=2),
        mc(Q + "How (　　) have you known Mr. Sato?", ["long", "many", "much", "often"], "期間をたずねるときは How long。", d=2),
        mc(Q + "It has been (　　) since this morning.", ["raining", "rained", "rain", "rains"], "have been ＋ -ing の現在完了進行形で「ずっと～し続けている」。", d=2),
        sa("次の2つの英文の内容を、現在完了を使って1文で表しなさい。\nI lost my key. I don't have it now.", "I have lost my key.",
           "過去になくして今も持っていない状態は現在完了（完了・結果）で表す。", d=3, v=["I've lost my key."]),
        mc(Q + "I (　　) him yesterday.", ["saw", "have seen", "have saw", "has seen"], "yesterday のように過去のある時点を表す語句は現在完了と一緒に使えない。", d=3),
    ]),
    U("JH-ENG-G3-U02", [
        mc(Q + "Look at the boy (　　) under the tree.", ["sitting", "sat", "sits", "to sit"], "「木の下にすわっている少年」。現在分詞が後ろから名詞を修飾する。", d=1),
        mc(Q + "This is a car (　　) in Japan.", ["made", "making", "make", "makes"], "「日本で作られた車」。過去分詞が後ろから修飾する。", d=1),
        mc(Q + "The language (　　) in Brazil is Portuguese.", ["spoken", "speaking", "speaks", "spoke"], "「ブラジルで話されている言語」なので過去分詞。", d=2),
        mc(Q + "Who is the girl (　　) with Tom?", ["talking", "talked", "talks", "to talking"], "「トムと話している少女」なので現在分詞。", d=2),
        mc(Q + "The book (　　) yesterday was very interesting.", ["I read", "I reading", "reading I", "read I"], "主語＋動詞のまとまりが名詞を後ろから修飾する（接触節）。", d=2),
        sa("日本語に合うように、（　）に入る1語を書きなさい。\n私は英語で書かれた手紙を受け取った。\nI got a letter (　　) in English.", "written", "「書かれた」なので write の過去分詞。", d=2),
        order(O + "これは私の父がとった写真です。", ["this is", "a picture", "my father", "took"], "This is a picture my father took. my father took が a picture を後ろから修飾する。", d=3),
        mc("次の英文の意味として最も適切なものを選びなさい。\nThe man standing by the door is my uncle.", ["ドアのそばに立っている男性は、私のおじです。", "男性はドアのそばに立って、おじを待っています。",
                                                                                         "私のおじはドアのそばに男性を立たせています。", "ドアのそばに立っていたのは、私のおじではありません。"],
           "standing by the door が The man を後ろから修飾し、文の動詞は is。", d=3, k=["grammar", "reading"]),
    ]),
    U("JH-ENG-G3-U03", [
        mc(Q + "I have a friend (　　) lives in Osaka.", ["who", "which", "whose", "what"], "先行詞が人（a friend）で、後ろに動詞が続くので主格の who。", d=1),
        mc(Q + "This is the train (　　) goes to Nagoya.", ["which", "who", "whom", "what"], "先行詞が物で主格なので which（that も可）。", d=1),
        mc(Q + "The cake (　　) my mother made was delicious.", ["that", "who", "what", "whose"], "先行詞が物で、後ろに主語＋動詞が続く目的格。that（which）を使う。", d=2),
        mc(Q + "She is the singer (　　) everyone knows.", ["that", "which", "what", "she"], "先行詞が人の目的格。that（whom / who）を使う。", d=2),
        sa("2つの英文を、関係代名詞を使って1文にしなさい。\nI know a boy. He can speak French.", "I know a boy who can speak French.", "He を主格の関係代名詞 who にかえて a boy の後ろにつなぐ。", d=2,
           v=["I know a boy that can speak French."]),
        sa("2つの英文を、関係代名詞を使って1文にしなさい。\nThis is the bag. I bought it last week.", "This is the bag which I bought last week.",
           "it を目的格の関係代名詞 which（that）にかえて the bag の後ろに置く。関係代名詞を省略してもよい。", d=3,
           v=["This is the bag that I bought last week.", "This is the bag I bought last week."]),
        mc("次の英文の下線部と同じ用法の that を含むものを選びなさい。\nThe movie [[u:that]] I saw was exciting.",
           ["The dog that is running there is mine.", "I think that she is kind.", "That is my school.", "I know that boy."],
           "問題文と選択肢1の that はいずれも関係代名詞。2は接続詞、3は代名詞、4は指示語（形容詞）。", d=4, k=["grammar", "thinking"]),
        order(O + "私が昨日会った女性は先生です。", ["the woman", "I met", "yesterday", "is", "a teacher"], "The woman I met yesterday is a teacher. 主語の名詞を接触節が修飾している。", d=4),
    ]),
    U("JH-ENG-G3-U04", [
        mc(Q + "Do you know (　　)?", ["where he lives", "where does he live", "where lives he", "where he does live"], "間接疑問文は「疑問詞＋主語＋動詞」の語順。", d=1),
        mc(Q + "Please tell me (　　) the station is.", ["where", "what", "who", "which"], "「駅がどこにあるか」なので where。", d=1),
        mc(Q + "My father gave (　　) a watch.", ["me", "my", "I", "mine"], "give ＋人＋物（SVOO）。人は目的格。", d=1),
        mc(Q + "We call our dog (　　).", ["Shiro", "for Shiro", "to Shiro", "Shiro's"], "call A B（A を B と呼ぶ）の SVOC。", d=2),
        mc(Q + "The news made (　　) happy.", ["us", "we", "our", "to us"], "make A B（A を B にする）。A は目的格。", d=2),
        mc(Q + "It is important (　　) us to read books.", ["for", "of", "to", "with"], "It is ～ for 人 to ―で「人が―することは～だ」。", d=2),
        mc(Q + "My mother let me (　　) her car.", ["use", "to use", "using", "used"], "let ＋人＋動詞の原形で「人に～させる（許可）」。", d=3),
        sa("次の2つの文を1文にしなさい。\nI don't know. When will the concert start?\n→ I don't know (　　).", "when the concert will start",
           "間接疑問文では疑問詞の後を「主語＋動詞」の語順にする。", d=3),
    ]),
    U("JH-ENG-G3-U05", [
        mc(Q + "If I (　　) a bird, I could fly to you.", ["were", "am", "be", "will be"], "現在の事実と異なる仮定は仮定法過去。be 動詞は主語にかかわらず were を使うのが一般的。", d=1),
        mc(Q + "I wish I (　　) a sister.", ["had", "have", "has", "will have"], "I wish ＋仮定法過去で「～ならいいのに」。", d=1),
        mc(Q + "If I had time, I (　　) go shopping with you.", ["would", "will", "can", "am"], "仮定法過去の主節は would / could ＋動詞の原形。", d=2),
        mc("次の英文の意味として最も適切なものを選びなさい。\nIf I knew her address, I would write to her.", ["彼女の住所を知らないので、手紙を書けない。", "彼女の住所を知っているので、手紙を書くつもりだ。",
                                                                                        "彼女の住所を知ったら、手紙を書くだろう。", "彼女の住所を知っていたので、手紙を書いた。"],
           "仮定法過去は現在の事実と反対のことを仮定する。実際は住所を知らない。", d=2, k=["grammar", "reading"]),
        mc("次の英文と同じ内容を表すものを選びなさい。\nI'm sorry I can't speak English well.", ["I wish I could speak English well.", "I wish I can speak English well.",
                                                                                 "If I speak English well, I'm sorry.", "I could speak English well."],
           "「上手に話せないのが残念だ」＝「上手に話せたらいいのに」。I wish I could ～。", d=3),
        mc(Q + "If it (　　) fine tomorrow, we will play baseball.", ["is", "were", "would be", "will be"], "実現の可能性がある未来の条件は、仮定法ではなく直説法。if の文の中は現在形。", d=3, k=["grammar", "thinking"]),
        sa("日本語に合うように、（　）に入る1語を書きなさい。\nもし私があなたなら、そんなことはしないだろう。\nIf I (　　) you, I wouldn't do that.", "were", "仮定法過去の be 動詞は were。", d=2),
        order(O + "もっとお金があれば、新しいコンピュータが買えるのに。", ["if I", "had", "more money", "I could buy", "a new computer"],
              "If I had more money, I could buy a new computer.", d=4),
    ]),
    U("JH-ENG-G3-U06", [
        mc("本文の内容に合うものを選びなさい。", ["Sora started the project to help foreign students.", "Sora made the map alone.", "The map was written only in English.", "Mr. Lee didn't like the map."],
           "第1段落に I wanted to help foreign students とある。地図は友達と一緒に、日本語と英語で作った。", d=2, k=R, st="READ1"),
        mc("Why did Sora decide to make the map?", ["Because Mr. Lee got lost on his first day.", "Because her teacher told her to make it.", "Because she wanted to win a contest.", "Because she liked drawing pictures."],
           "Mr. Lee が初日に道に迷ったと聞いたことがきっかけ。", d=2, k=R, st="READ1"),
        mc("本文中の [[u:it]] が指すものを選びなさい。（第2段落 3 文目）", ["the map", "the school", "the station", "the city"],
           "We finished it after two weeks. の it は直前に出てくる the map（地図）を指す。", d=3, k=R, st="READ1"),
        mc("What did Sora learn from the project?", ["Small actions can help people.", "Making maps is easy.", "English is not important.", "Foreign students don't need help."],
           "最終段落で Small actions can help people. と述べている。", d=3, k=R, st="READ1"),
        mc("グラフの内容に合うものを選びなさい。", ["朝食を毎日食べる生徒は全体の半数以上である", "朝食をまったく食べない生徒が最も多い", "朝食を週に数回食べる生徒は 40% である", "朝食を毎日食べる生徒は 30% である"],
           "Every day が 62% で半数以上。Never は 8%、Sometimes は 30%。", d=2, k=["reading", "data_interpretation"], st="READ2"),
        mc("Why does Mr. Smith say breakfast is important?", ["Because it gives us energy for the morning.", "Because it is cheap.", "Because students like it.", "Because it makes us sleepy."],
           "It gives us energy for the morning. とある。", d=2, k=R, st="READ2"),
        mc("What does Mr. Smith want students to do?", ["Get up a little earlier and eat breakfast.", "Eat lunch at home.", "Skip breakfast on weekends.", "Drink only water in the morning."],
           "So I want you to get up a little earlier and eat breakfast. と述べている。", d=3, k=R, st="READ2"),
        desc("あなたは朝食を食べることについて、どう考えるか。理由を1つ加えて、2文以上の英語で書きなさい。",
             "I think eating breakfast is important. When I eat breakfast, I can study hard in the morning.",
             "I think ～. のように意見を述べ、Because ～. / When ～. などで理由を続ける。", [("意見を明確に述べている", 2), ("理由を述べている", 2), ("文法・つづりの誤りがない", 1)],
             d=4, k=W, lines=3),
    ], stimuli=[
        stim("READ1", "Last spring, a new teacher from Singapore, Mr. Lee, came to our school. On his first day, he got lost on his way from the station. When I heard about it, I wanted to help foreign students and teachers in our city.\n\n"
             "So my friends and I decided to make a map of our town. We walked around the town and took notes about shops, parks, and the hospital. We finished it after two weeks. The map was written in Japanese and English.\n\n"
             "We gave the map to Mr. Lee. He smiled and said, \"This is very useful. Thank you!\" Now the map is in the city hall, and many people use it.\n\n"
             "Through this project, I learned that small actions can help people. I want to do more things for people in my town.",
             "passage", "次の英文は、中学生の Sora が書いたものである。", source="オリジナル", glossary=[("get lost", "道に迷う"), ("city hall", "市役所")]),
        stim("READ2", "Mr. Smith: Look at this graph. We asked 200 students in our school, \"How often do you eat breakfast?\" Sixty-two percent of the students eat breakfast every day. "
             "But eight percent never eat breakfast. Breakfast is important because it gives us energy for the morning. So I want you to get up a little earlier and eat breakfast.",
             "passage", "次の英文は、ALT のスミス先生が授業で話した内容である。", source="オリジナル",
             tbl=table([["Every day", "62%"], ["Sometimes", "30%"], ["Never", "8%"]], header=["How often do you eat breakfast?", "Students"])),
    ]),
    U("JH-ENG-G3-U07", [
        order(O + "私はあなたにこの本を読んでもらいたい。", ["I want", "you", "to read", "this book"], "want ＋人＋ to ～で「人に～してもらいたい」。", d=2, k=W),
        order(O + "ピアノをひいている女の子は私の妹です。", ["the girl", "playing", "the piano", "is", "my sister"], "現在分詞 playing the piano が the girl を後ろから修飾する。", d=3, k=W),
        sa("次の日本語を英語に直しなさい。\n私はまだ宿題を終えていません。", "I haven't finished my homework yet.", "現在完了の否定文。「まだ」は文末の yet。", d=3, k=W, v=["I have not finished my homework yet."]),
        sa("次の日本語を英語に直しなさい。\n英語を話すことは私にとって簡単ではありません。", "It is not easy for me to speak English.", "It is ～ for 人 to ―の形を使う。Speaking English is not easy for me. でもよい。",
           d=3, k=W, v=["Speaking English is not easy for me.", "It isn't easy for me to speak English."]),
        desc("次の質問に、理由を含めて2文以上の英語で答えなさい。\nWhich do you like better, summer or winter?",
             "I like winter better than summer. I can enjoy skiing with my family in winter.",
             "質問の語句を使って I like ～ better (than …). と答え、理由を続ける。", [("質問に正しく答えている（比較の表現）", 2), ("理由を述べている", 2), ("文法・つづりの誤りがない", 1)], d=4, k=W, lines=3),
        desc("あなたの学校に来る留学生に、学校生活のアドバイスを2文以上の英語で書きなさい。",
             "You should join a club activity. You can make many friends there.",
             "should / can などの助動詞を使うとアドバイスを表しやすい。", [("アドバイスの内容が伝わる", 2), ("2文以上で具体的に書いている", 2), ("文法・つづりの誤りがない", 1)], d=4, k=W, lines=3),
        desc("「あなたが将来したいこと」について、3文以上の英語で書きなさい。",
             "I want to be a nurse in the future. I want to help sick people. So I will study science hard.",
             "want to be ～ / want to ～ で夢を述べ、理由や今していることを加える。", [("将来したいことを述べている", 2), ("理由・具体的な内容を加えている", 2), ("3文以上で、文法・つづりの誤りがない", 1)], d=5, k=W, lines=4),
        sa("次の日本語を英語に直しなさい。\nもし明日雨が降ったら、私は家にいます。", "If it rains tomorrow, I will stay home.", "条件を表す if の文の中は未来のことでも現在形。", d=3, k=W,
           v=["I will stay home if it rains tomorrow.", "If it rains tomorrow, I'll stay home."]),
    ]),
]
